"""create seed tables

Revision ID: 23036c00c37f
Revises: 
Create Date: 2026-01-18 14:58:09.215419

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '23036c00c37f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alcohol_levels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('difficulties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occasions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vibes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cocktails',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('difficulty_id', sa.String(), nullable=False),
    sa.Column('alcohol_level_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['alcohol_level_id'], ['alcohol_levels.id'], ),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cocktail_occasions',
    sa.Column('cocktail_id', sa.String(), nullable=False),
    sa.Column('occasion_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ),
    sa.ForeignKeyConstraint(['occasion_id'], ['occasions.id'], ),
    sa.PrimaryKeyConstraint('cocktail_id', 'occasion_id')
    )
    op.create_table('cocktail_vibes',
    sa.Column('cocktail_id', sa.String(), nullable=False),
    sa.Column('vibe_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ),
    sa.ForeignKeyConstraint(['vibe_id'], ['vibes.id'], ),
    sa.PrimaryKeyConstraint('cocktail_id', 'vibe_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cocktail_vibes')
    op.drop_table('cocktail_occasions')
    op.drop_table('cocktails')
    op.drop_table('vibes')
    op.drop_table('occasions')
    op.drop_table('difficulties')
    op.drop_table('alcohol_levels')
    # ### end Alembic commands ###
