"""add cocktail detail fields

Revision ID: a2dd7a4585b2
Revises: f4e82e5dbf9c
Create Date: 2026-01-20 13:25:00.250117

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'a2dd7a4585b2'
down_revision = 'f4e82e5dbf9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cocktails', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('cocktails', sa.Column('glassware', sa.String(), nullable=True))
    op.add_column('cocktails', sa.Column('garnish', sa.String(), nullable=True))
    op.add_column('cocktails', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cocktails', 'tags')
    op.drop_column('cocktails', 'garnish')
    op.drop_column('cocktails', 'glassware')
    op.drop_column('cocktails', 'image_url')
    # ### end Alembic commands ###
