"""add cocktails rank

Revision ID: f4e82e5dbf9c
Revises: fc26e01b04be
Create Date: 2026-01-19 22:18:24.108331

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'f4e82e5dbf9c'
down_revision = 'fc26e01b04be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'cocktails',
        sa.Column('rank', sa.Integer(), nullable=False, server_default=sa.text('0')),
    )
    op.alter_column('cocktails', 'rank', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cocktails', 'rank')
    # ### end Alembic commands ###
