"""create seed tables

Revision ID: fc26e01b04be
Revises: 23036c00c37f
Create Date: 2026-01-18 16:31:08.405215

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'fc26e01b04be'
down_revision = '23036c00c37f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
